#!/bin/bash

echo ""
echo "Creating $1"

REMOTE_VOTING=jrootham@jrootham.ca:voting
REMOTE_DOCROOT=website@jrootham.ca:httpdocs/voting/$1
SUFFIX=resources/public/

PREFIX=/home/jrootham/dev/cabal/cabalVoting/voting-server
UBERJAR=/target/uberjar/voting-server.jar
VOTING=/home/jrootham/dev/cabal/cabalVoting
DOCROOT=/home/jrootham/dev/cabal/cabalVoting/docroot

ssh jrootham.ca "mkdir -p voting/servers/$1/"
ssh jrootham.ca "mkdir -p voting/supervisor/"

rsync -v $VOTING/supervisor/$1.service $REMOTE_VOTING/supervisor

rsync -v $DOCROOT/* $REMOTE_DOCROOT

cd voting-server

ln -sf $PREFIX/src/voting_server/$1stuff.clj $PREFIX/src/voting_server/stuff.clj

lein uberjar

rsync -v $PREFIX$UBERJAR $REMOTE_VOTING/servers/$1

